server:
  port: 8083

spring:
  application:
    name: catalog-service
  devtools:
    livereload:
      port: 35730

#Data Source Properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/catalog?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

#JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: FALSE
        show_sql: FALSE
    hibernate:
      ddl-auto: validate

  #Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082

  #Pagination
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #Zipkin
  zipkin:
    base-url: http://localhost:9411

#Show SQL executed with parameter bindings
#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        oauth2: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#Prometheus (and other data loggers)
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
