server:
  port: 8082

spring:
  application:
    name: auth-service
  devtools:
    livereload:
      port: 35730

  #Data Source Properties
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_DB_USER}
      database: authentication
      port: 27017
      host: localhost

  #Zipkin
  zipkin:
    base-url: http://localhost:9411

#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        oauth2: INFO

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Prometheus (and other data loggers)
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true


