spring:
  threads:
    virtual:
      enabled: true

  #Data Source Properties
  data:
    mongodb:
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: ${MONGO_DB_DATABASE}
      authentication-database: admin
      port: 27017
      host: localhost

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/registered_client

  #JPA Properties
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        web: INFO
        security: TRACE
        oauth2: INFO
        vault: DEBUG
        cloud.vault: DEBUG
    io:
      github:
        resilience4j: ERROR
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"

auth:
  issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8082}
  jwk:
    location: ${AUTH_JWK_DIR:./.localkeys}

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0  # 100% for development
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs