spring:
  #Data Source Properties
  mongodb:
    username: ${MONGO_DB_USERNAME}
    password: ${MONGO_DB_PASSWORD}
    database: ${MONGO_DB_DATABASE}
    port: 27017
    host: localhost

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/registered_client

  #JPA Properties
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        web: INFO
        security: TRACE
        oauth2: INFO
        vault: DEBUG
        cloud.vault: DEBUG

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Prometheus (and other data loggers)
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"