server:
  port: 8082

spring:
  application:
    name: auth-service
  devtools:
    livereload:
      port: 35730
  cloud:
    vault:
      authentication: TOKEN
      token: ${VAULT_SERVER_TOKEN}
      uri: http://localhost:8200
      application-name: auth-service/dev
      kv:
        backend: secret
        enabled: true
        default-context: auth-service/dev

    compatibility-verifier:
      enabled: false

  config:
    import: optional:vault://

  #Security
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/{registrationId}
            scope:
              - openid
              - email
              - profile
          github:
            provider: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/{registrationId}
          facebook:
            provider: facebook
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/{registrationId}
        provider:
          google:
            issuer-uri: https://accounts.google.com
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          github:
            #issuer-uri: https://token.actions.githubusercontent.com
            jwk-set-uri: https://token.actions.githubusercontent.com/.well-known/jwks
          facebook:
            #issuer-uri: https://www.facebook.com
            authorization-uri: https://facebook.com/dialog/oauth/
            jwk-set-uri: https://www.facebook.com/.well-known/oauth/openid/jwks/


  #Data Source Properties
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_DB_USER}
      password: ${MONGO_DB_PASSWORD}
      database: authentication
      port: 27017
      host: localhost
      auto-index-creation: true

  #Data Source Properties
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/registered_clients

  #JPA Properties
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  #Zipkin
  zipkin:
    base-url: http://localhost:9411

  #Kafka
  kafka:
    bootstrap-servers: localhost:29092
#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        oauth2: INFO
      hibernate:
        SQL: off
        type:
          descriptor: off
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#    enabled: false

#Prometheus (and other data loggers)
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

keyManager:
  algorithm: "RSA"
  keySize: 2048