services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
    networks:
      - mongodb-network

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/data/postgres
      - ./postgresql-init/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"

  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    #    Prod
    #    volumes:
    #      - ./vault/config:/helpers
    #      - ./vault/data:/vault/data
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: "http://0.0.0.0:8200"
    command: vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200
    #    Prod
    #    command: vault server -config=/helpers/vault-config.hcl
    networks:
      - vault-network
    healthcheck:
      test: [ "CMD-SHELL", "vault status >/dev/null 2>&1 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5

  vault-init:
    image: hashicorp/vault:1.17
    container_name: vault-init
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ROLE_ID: ${VAULT_ROLE_ID}
      VAULT_SECRET_ID: ${VAULT_SECRET_ID}
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      FLYWAY_PROFILE: ${FLYWAY_PROFILE}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_EXPRESS_USER: ${MONGO_EXPRESS_USER}
      MONGO_EXPRESS_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ECOMMERCE_OAUTH2_CLIENT_ID: ${ECOMMERCE_OAUTH2_CLIENT_ID}
      ECOMMERCE_OAUTH2_SECRET: ${ECOMMERCE_OAUTH2_SECRET}
      GATEWAY_CLIENT_ID: ${GATEWAY_CLIENT_ID}
      GATEWAY_CLIENT_SECRET: ${GATEWAY_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      PASSWORD_RESET_TOKEN_SECRET_KEY: ${PASSWORD_RESET_TOKEN_SECRET_KEY}
    networks:
      - vault-network
    volumes:
      - ./vault/init-secrets.sh:/init-secrets.sh
      - ./vault/data:/vault/data
    entrypoint: [ "sh", "/init-secrets.sh" ]

  vault-agent:
    image: hashicorp/vault:1.17
    container_name: vault-agent
    restart: always
    volumes:
      - ./vault/config:/helpers
      - ./vault/data:/vault
    environment:
      VAULT_ADDR: http://vault:8200
    networks:
      - vault-network
    depends_on:
      vault:
        condition: service_healthy
    command: >
      sh -c "
      echo \"$VAULT_ROLE_ID\" > /vault/role-id &&
      echo \"$VAULT_SECRET_ID\" > /vault/secret-id &&
      vault agent -config=/helpers/vault-agent.hcl
      "

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: unless-stopped

  eureka-server-1:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server-1
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server-1
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    ports:
      - "8761:8761"
    restart: unless-stopped
    networks:
      - eureka-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

  eureka-server-2:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server-2
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server-2
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    ports:
      - "8762:8761"
    restart: unless-stopped
    networks:
      - eureka-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  data:
  postgres:
  vault_data:

networks:
  mongodb-network:
    driver: bridge
  vault-network:
    driver: bridge
  eureka-network:
    driver: bridge