version: '3.8'
services:
  db:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: catalog
      MYSQL_USERNAME: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    networks:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_EXPRESS_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_EXPRESS_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
    links:
      - mongodb

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - spring

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - grafana/config.monitoring
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9100:9100"
    restart: always

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: always

  vault:
    image: hashicorp/vault
    restart: always
    volumes:
      - ./vault/config/:/helpers
      - vault_data:/vault/file
    ports:
      - "8201:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault
    entrypoint: "vault server -config=/helpers/vault-config.hcl"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8200 || exit 1
      interval: 10s
      retries: 12
      start_period: 10s
      timeout: 10s

  vault-agent:
    image: hashicorp/vault
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config/:/helpers
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    container_name: vault-agent
    networks:
      - spring
      - vault
    entrypoint: "vault agent -log-level debug -config=/helpers/vault-agent.hcl"
    depends_on:
      vault:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - spring

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - spring

  eureka-server:
    image: dgganchev/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  auth-server:
    image: dgganchev/authentication:latest
    container_name: auth-server
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_SERVER_TOKEN=${VAULT_SERVER_TOKEN}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - vault
      - spring
      - postgres
      - mongodb
    depends_on:
      - zipkin
      - eureka-server
      - prometheus
      - vault
      - mongodb
      - postgres

  gateway:
    image: dgganchev/gateway:latest
    container_name: gateway-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_SERVER_TOKEN=${VAULT_SERVER_TOKEN}
      - GATEWAY_CLIENT_ID=${GATEWAY_CLIENT_ID}
      - GATEWAY_CLIENT_SECRET=${GATEWAY_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
      - prometheus
      - vault
      - auth-server

  catalog:
    image: dgganchev/catalog:latest
    container_name: catalog-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_SERVER_TOKEN=${VAULT_SERVER_TOKEN}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - GATEWAY_CLIENT_ID=${GATEWAY_CLIENT_ID}
      - GATEWAY_CLIENT_SECRET=${GATEWAY_CLIENT_SECRET}
    networks:
      - spring
      - mysql
    depends_on:
      - zipkin
      - eureka-server
      - prometheus
      - vault
      - db

  order:
    image: dgganchev/order:latest
    container_name: order-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_SERVER_TOKEN=${VAULT_SERVER_TOKEN}
      - GATEWAY_CLIENT_ID=${GATEWAY_CLIENT_ID}
      - GATEWAY_CLIENT_SECRET=${GATEWAY_CLIENT_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: java -Djava.security.egd=file:/dev/./urandom -jar /project/target/order-0.0.1-SNAPSHOT.jar
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - prometheus
      - vault
      - postgres
      - kafka

  profile:
    image: dgganchev/profile:latest
    container_name: profile-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_SERVER_TOKEN=${VAULT_SERVER_TOKEN}
      - ECOMMERCE_OAUTH2_CLIENTID=${ECOMMERCE_OAUTH2_CLIENTID}
      - ECOMMERCE_OAUTH2_SECRET=${ECOMMERCE_OAUTH2_SECRET}
      - MONGO_DB_PASSWORD=rootpassword
      - MONGO_DB_USER=rootuser
      - PASSWORD_RESET_TOKEN_SECRET_KEY=${PASSWORD_RESET_TOKEN_SECRET_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GATEWAY_CLIENT_ID=${GATEWAY_CLIENT_ID}
      - GATEWAY_CLIENT_SECRET=${GATEWAY_CLIENT_SECRET}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8083
    networks:
      - spring
      - mongodb
    depends_on:
      - zipkin
      - eureka-server
      - prometheus
      - vault
      - mongodb
      - kafka

  notification:
    image: dgganchev/notification:latest
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_SERVER_TOKEN=${VAULT_SERVER_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - prometheus
      - vault
      - postgres
      - kafka

  payment:
    image: dgganchev/payment:latest
    container_name: payment-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - VAULT_SERVER_TOKEN=${VAULT_SERVER_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - prometheus
      - vault
      - postgres

networks:
  postgres:
    driver: bridge
  mongodb:
    driver: bridge
  mysql:
    driver: bridge
  spring:
    driver: bridge
  vault:
    driver: bridge
volumes:
  db:
  prometheus_data: { }
  grafana_storage: { }
  data: { }
  postgres:
  vault_data: { }
