server:
  port: 8083

spring:
  application:
    name: profile-service
  devtools:
    livereload:
      port: 35730
  profiles:
    include: dev
  cloud:
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${VAULT_SERVER_TOKEN}
      generic:
        enable: true
        backend: auth-service
        default-context: credentials
  #Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8082
          jwk-set-uri: http://auth-server:8082/oauth2/jwks
      client:
        registration:
          gateway-client-oidc:
            provider: spring
            client-id: ${$GATEWAY_CLIENT_ID}
            client-secret: ${GATEWAY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            redirect-uri: "http://gateway:8081/login/oauth2/code/{registrationId}"
        provider:
          spring:
            issuer-uri: http://auth-server:8082
            authorization-uri: http://auth-server:8082/oauth2/authorize
            token-uri: http://auth-server:8082/oauth2/token

  #Data Source Properties
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_DB_USER}
      password: ${MONGO_DB_PASSWORD}
      database: authentication
      port: 27017
      host: mongodb
      auto-index-creation: true

  #Pagination
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #Zipkin
  zipkin:
    base-url: http://zipkin:9411

#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        data: INFO
        web: INFO
        security: INFO
        oauth2: INFO

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

#Prometheus (and other data loggers)
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

#Spring Doc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    oauth2RedirectUrl: http://gateway:8081/login/oauth2/code/gateway-client-oidc
    oauth:
      client-id: gateway
      client-secret: secret
      scopes:
        - openid
        - profile.read
        - profile.write
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: http://auth-server:8082/oauth2/authorize
    tokenUrl: http://auth-server:8082/oauth2/token

#Kafka
kafka:
  bootstrapAddress: kafka:9092

#Resilience4j
resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      minimumNumberOfCalls: 10
      slidingWindowType: TIME_BASED
      slidingWindowSize: 10
      waitDurationInOpenState: 1000
      permittedNumberOfCallsInHalfOpenState: 5
      registerHealthIndicator: true
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    profileService:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
      cancelRunningFuture: true
  instances:
    profileService:
      baseConfig: default

#JWT secret key
jwt:
  secret:
    key: ${PASSWORD_RESET_TOKEN_SECRET_KEY}

payment:
  base:
    uri: http://payment:8087/api/v1
  service:
    customer:
      post:
        uri: ${payment.base.uri}/payment/customer/create-customer
      get:
        uri: ${payment.base.uri}/payment/customer/get-customer?username=
      delete:
        uri: ${payment.base.uri}/payment/customer/delete-customer?username=
    card:
      post:
        uri: ${payment.base.uri}/payment/card/create-card
      get:
        uri: ${payment.base.uri}/payment/card/get-customer-cards?username=

webClient:
  oath2Client:
    defaultClientRegistrationId: "gateway-client-oidc"

github:
  clientId: ${GITHUB_CLIENT_ID}
  secret: ${GITHUB_SECRET}
ecommerce:
  oauth2:
    clientId: ${ECOMMERCE_OAUTH2_CLIENTID}
    secret: ${ECOMMERCE_OAUTH2_SECRET}

