server:
  port: 8085

spring:
  application:
    name: notification-service
  devtools:
    livereload:
      port: 35730
  cloud:
    vault:
      authentication: TOKEN
      token: ${VAULT_SERVER_TOKEN}
      kv:
        enabled: true
      scheme: http
      host: vault-agent
      port: 8201
      application-name: notification-service/docker
      generic:
        enabled: true
        backend: notification-service

  config:
    import: optional:vault://
  #Data Source Properties
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres:5432/notification

  #JPA Properties
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  #Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8082
          jwk-set-uri: http://auth-server:8082/oauth2/jwks

  #Pagination
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #Zipkin
  zipkin:
    base-url: http://zipkin:9411

  #Gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#Show SQL executed with parameter bindings
#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        oauth2: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false


#Prometheus (and other data loggers)
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

#Spring Doc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    oauth2RedirectUrl: http://gateway-service:8081/login/oauth2/code/gateway-client-oidc
    oauth:
      client-id: gateway
      client-secret: secret
      scopes:
        - openid
        - notification.read
        - notification.write
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: http://auth-server:8082/oauth2/authorize
    tokenUrl: http://auth-server:8082/oauth2/token

#Kafka
kafka:
  bootstrapAddress: kafka:9092