server:
  port: 8081

spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      client:
        registration:
          gateway-client-oidc:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/login/oauth2/code/{registrationId}"
            scope: openid, auth.user
            client-name: gateway-client-oidc
        provider:
          spring:
            issuer-uri: http://localhost:8082

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            Path=/api/v1/catalog/**
          filters:
            TokenRelay=
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/profile/**
          filters:
            - TokenRelay=
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - TokenRelay=
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: 'true'
    metrics:
      enabled: 'true'
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka