server:
  port: 8083

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/v1/profile/**
        - id: catalog
          uri: lb://CATALOG
          predicates:
            - Path=/api/v1/catalog/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: 'true'
    metrics:
      enabled: 'true'
  metrics:
    export:
      prometheus:
        enabled: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka