server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      client:
        registration:
          catalog-client-oidc:
            provider: spring
            client-id: catalog-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: catalog-client-oidc
          catalog-client-authorization-code:
            provider: spring
            client-id: catalog-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/authorized"
            scope: articles.read
            client-name: catalog-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:8082
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    prometheus:
      enabled: 'true'
    metrics:
      enabled: 'true'
#    gateway:
#      enabled: true
  metrics:
    export:
      prometheus:
        enabled: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka