server:
  port: 8081

spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      client:
        registration:
          gateway-client-oidc:
            provider: gateway-provider
            client-id: gateway-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/login/oauth2/code/{registrationId}"
            scope: openid, auth.user
            client-name: gateway-client-oidc
        provider:
          gateway-provider:
            issuer-uri: http://localhost:8082
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8083
          predicates:
            Path=/api/v1/catalog/**
          filters:
            TokenRelay=
        - id: profile-service
          uri: http://localhost:8084
          predicates:
            Path=/api/v1/profile/**
          filters:
            TokenRelay=

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: 'true'
    metrics:
      enabled: 'true'
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka