server:
  port: 8333

spring:
  #Data Source Properties
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_DB_USER}
      password: ${MONGO_DB_PASSWORD}
      database: opaque_introspector
      port: 27017
      host: localhost
      auto-index-creation: true

  #Zipkin
  zipkin:
    base-url: http://localhost:9411

#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        data: INFO
        web: INFO

management:
  tracing:
    sampling:
      probability: 1.0  # 100% for development
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  health:
    circuitbreakers:
      enabled: true