server:
  port: 8333

spring:
  #Zipkin
  zipkin:
    base-url: http://localhost:9411

#Logging Levels
#Disable the default loggers
logging:
  level:
    blog: WARN
    root: INFO
    org:
      springframework:
        data: INFO
        web: INFO

management:
  tracing:
    sampling:
      probability: 1.0  # 100% for development
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  health:
    circuitbreakers:
      enabled: true