server:
  port: 8087
  servlet:
    context-path: /config

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/IdeaProjects/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true